<!doctype html><html lang="pt-BR"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Enviar fotos da correção</title>
<style>*{box-sizing:border-box}body{margin:0;padding:18px;background:#172236;color:#edf3fb;font:16px system-ui}.box{max-width:520px;margin:auto;padding:22px;border:1px solid #43536c;border-radius:16px;background:#253248}.card{margin:14px 0;padding:14px;border:1px solid #4b5d78;border-radius:10px;background:#1d293d}.pick{display:block;padding:14px;border:2px dashed #7184a0;border-radius:9px;text-align:center;font-weight:700;cursor:pointer}.pick input{position:absolute;width:1px;height:1px;opacity:0}.preview{display:grid;grid-template-columns:58px 1fr auto;gap:9px;align-items:center;margin-top:10px;color:#c3cede;font-size:12px}.preview img{width:58px;height:58px;object-fit:cover;border-radius:7px}.preview button,button{border:0;border-radius:8px;padding:10px;background:#b84249;color:#fff;font-weight:800;cursor:pointer}button[type=submit]{width:100%;margin-top:14px;padding:14px}.note{padding:11px;border-radius:8px;background:#203a57;color:#cce0f4;font-size:13px}.ok{padding:12px;border-radius:8px;background:#234c3d;color:#a6e9bd}</style>
<main class="box"><h1>Comprovação fotográfica</h1><p>Envie a foto da identificação e a foto da leitura. As imagens devem apresentar data/hora e coordenadas de localização.</p>
@if($mode === 'pending')<form method="post" enctype="multipart/form-data" action="{{ route('reading-corrections.evidence.upload',$token) }}">@csrf
<section class="card"><strong>Foto da placa/identificação</strong><p>Fotografe a placa, código ou característica legível do veículo/equipamento.</p><label class="pick">Selecionar imagem<input type="file" name="plate_photo" accept="image/*" capture="environment"></label><div class="preview" data-preview="plate_photo"></div></section>
<section class="card"><strong>Foto do hodômetro/horímetro</strong><p>Fotografe o painel mostrando claramente a leitura.</p><label class="pick">Selecionar imagem<input type="file" name="reading_photo" accept="image/*" capture="environment"></label><div class="preview" data-preview="reading_photo"></div></section><button type="submit">Enviar fotos</button></form>
@elseif($mode === 'expired')<p class="note">Este link expirou. Gere outro QR Code no computador.</p>
@else<div class="ok"><strong>Fotos enviadas com sucesso.</strong><br>Você pode voltar ao computador e concluir a correção.</div>@endif</main>
<script>document.querySelectorAll('input[type=file]').forEach(input=>input.addEventListener('change',()=>{const f=input.files[0],p=document.querySelector(`[data-preview="${input.name}"]`);if(!f){p.innerHTML='';return}const u=URL.createObjectURL(f);p.innerHTML=`<img src="${u}" alt="Prévia"><span>${f.name}</span><button type="button">Remover</button>`;p.querySelector('button').onclick=()=>{input.value='';p.innerHTML=''}}));</script></html>
