<!doctype html>
<html lang="pt-BR"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Comprovação em vídeo</title>
<style>body{margin:0;background:#121b2d;color:#edf2f7;font:16px system-ui;padding:24px}main{max-width:500px;margin:auto;text-align:center}label,.card{display:block;margin:22px 0;padding:20px;border:1px dashed #789;border-radius:12px}.card{border-style:solid;text-align:left}input{display:none}button{width:100%;padding:14px;border:0;border-radius:9px;background:#b84249;color:#fff;font-weight:700;margin-top:12px}button.secondary{background:#33415d}.success{color:#8de0a3;font-size:46px;margin:24px 0 4px}.error{color:#f5a3a3;font-size:40px;margin:24px 0 4px}small,p{color:#aab6ca}.hidden{display:none}video{width:100%;max-height:260px;border-radius:8px;background:#000}.spinner{display:inline-block;width:16px;height:16px;border:2px solid #aab6ca;border-top-color:#fff;border-radius:50%;animation:spin .8s linear infinite;vertical-align:middle}@keyframes spin{to{transform:rotate(360deg)}}.details{display:flex;justify-content:space-between;color:#cbd5e1;font-size:14px;margin-top:10px}</style>
<main><h1>Comprovação em vídeo</h1><p>Veículo #{{ $evidence->vehicle_id }}</p>
@if($mode === 'pending')
    <p>Grave um vídeo de até 10 segundos mostrando a placa e o hodômetro/horímetro.</p>
    <form id="evidenceForm" method="post" enctype="multipart/form-data" action="{{ route('reading-corrections.evidence.upload',$token) }}">@csrf
        <label id="picker">Gravar / selecionar vídeo<input id="videoInput" name="video" type="file" accept="video/*" capture="environment" required></label>
        <p id="loading" class="hidden"><span class="spinner"></span> Carregando vídeo...</p>
        <section id="preview" class="card hidden"><strong>Prévia do vídeo</strong><video id="previewVideo" controls playsinline preload="metadata"></video><div class="details"><span id="duration">--:--</span><span id="size">--</span></div><p id="localError" class="hidden"></p><button type="button" class="secondary" id="replace">Trocar vídeo</button><button type="submit" id="send" disabled>Enviar vídeo</button></section>
        <p id="sending" class="hidden"><span class="spinner"></span> Enviando e processando vídeo...</p>
    </form>
    @error('video')<p>{{ $message }}</p>@enderror
@elseif($mode === 'processing')
    <div class="success">◌</div><h2>Vídeo em processamento...</h2><p>O vídeo foi recebido. Aguarde a conclusão antes de voltar ao computador.</p>
@elseif($mode === 'ready')
    <div class="success">✓</div><h2>Vídeo enviado com sucesso</h2><p>O vídeo foi recebido e processado.</p>@if($evidence->duration_seconds)<p>Duração: {{ number_format($evidence->duration_seconds, 2, ',', '.') }} s</p>@endif<p><strong>Volte ao computador para concluir a correção.</strong></p>
@elseif($mode === 'expired')
    <div class="error">!</div><h2>Sessão expirada</h2><p>Este link não pode mais ser usado. Gere uma nova sessão no computador.</p>
@else
    <div class="error">!</div><h2>Não foi possível processar o vídeo</h2><p>Esta sessão foi encerrada. Gere uma nova sessão no computador para tentar novamente.</p>
@endif
</main>
@if($mode === 'pending')<script>
const input=document.getElementById('videoInput'), preview=document.getElementById('preview'), player=document.getElementById('previewVideo'), loading=document.getElementById('loading'), send=document.getElementById('send'), replace=document.getElementById('replace'), error=document.getElementById('localError'), form=document.getElementById('evidenceForm'); let objectUrl=null, selectedVideoFile=null;
const formatSize=b=>b<1048576?(b/1024).toFixed(1)+' KB':(b/1048576).toFixed(1)+' MB'; const formatDuration=s=>`00:${s.toFixed(2).padStart(5,'0')}`;
function clearPreview(){if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=null;selectedVideoFile=null;player.removeAttribute('src');preview.classList.add('hidden');send.disabled=true;error.classList.add('hidden');}
function showError(message){error.textContent=message;error.classList.remove('hidden');send.disabled=false;replace.disabled=false;input.disabled=false;document.getElementById('picker').classList.remove('hidden');document.getElementById('sending').classList.add('hidden');}
input.addEventListener('change',()=>{const file=input.files[0];clearPreview();if(!file)return;selectedVideoFile=file;loading.classList.remove('hidden');objectUrl=URL.createObjectURL(selectedVideoFile);player.src=objectUrl;player.onloadedmetadata=()=>{loading.classList.add('hidden');preview.classList.remove('hidden');document.getElementById('duration').textContent=formatDuration(player.duration);document.getElementById('size').textContent=formatSize(selectedVideoFile.size);if(!Number.isFinite(player.duration)||player.duration>10){error.textContent=`Este vídeo possui ${player.duration.toFixed(2)} segundos. O limite é de 10 segundos.`;error.classList.remove('hidden');send.disabled=true;return;}send.disabled=false;};player.onerror=()=>{loading.classList.add('hidden');preview.classList.remove('hidden');error.textContent='Não foi possível ler os metadados deste vídeo. Escolha outro arquivo.';error.classList.remove('hidden');};});
replace.addEventListener('click',()=>{clearPreview();input.value='';input.click();});form.addEventListener('submit',async event=>{event.preventDefault();if(!(selectedVideoFile instanceof File)){showError('Selecione um vídeo antes de enviar.');return;}if(@json(config('app.debug')))console.debug('Video upload',{isFile:selectedVideoFile instanceof File,name:selectedVideoFile.name,size:selectedVideoFile.size,type:selectedVideoFile.type});send.disabled=true;replace.disabled=true;input.disabled=true;document.getElementById('picker').classList.add('hidden');document.getElementById('sending').classList.remove('hidden');const data=new FormData();data.append('_token',form.querySelector('[name=_token]').value);data.append('video',selectedVideoFile,selectedVideoFile.name);try{const response=await fetch(form.action,{method:'POST',headers:{'Accept':'application/json','X-CSRF-TOKEN':form.querySelector('[name=_token]').value},body:data,credentials:'same-origin'});if(response.status===422){const body=await response.json();showError(Object.values(body.errors||{}).flat().join(' ')||body.message||'Não foi possível enviar o vídeo.');return;}if(!response.ok)throw new Error(`HTTP ${response.status}`);window.location.assign(response.url);}catch(exception){console.error('Falha no envio do vídeo',exception);showError('Não foi possível enviar o vídeo. Tente novamente.');}});window.addEventListener('pagehide',clearPreview);
</script>@endif
</html>
