<div x-data="supplierAutocomplete()" x-init="init()" class="chm-supplier-picker" @keydown.escape="open=false">
    <input x-ref="name" name="{{ $textName ?? 'supplier_name' }}" value="{{ $value ?? '' }}" maxlength="255" placeholder="{{ $placeholder ?? 'Nome do fornecedor' }}" autocomplete="off" @if(isset($textModel)) x-model="{{ $textModel }}" @endif @input.debounce.300ms="changed()" @focus="onFocus()" aria-label="Fornecedor">
    <input x-ref="id" type="hidden" name="{{ $idName ?? 'supplier_id' }}" value="{{ $supplierIdValue ?? '' }}" @if(isset($idModel)) x-model="{{ $idModel }}" @endif>
    @if(isset($documentName))
        <input x-ref="document" type="text" name="{{ $documentName }}" value="{{ $documentValue ?? '' }}" maxlength="20" placeholder="{{ $documentPlaceholder ?? 'CPF ou CNPJ' }}" @if(isset($documentModel)) x-model="{{ $documentModel }}" @endif @input="documentChanged()" aria-label="CPF ou CNPJ do fornecedor">
    @endif
    <span x-show="loading && !selected" class="chm-supplier-picker__loading">Buscando fornecedores…</span>
    <div x-show="selected" class="chm-supplier-picker__selected"><strong x-text="selected?.name"></strong><button type="button" @click="clear()" aria-label="Limpar fornecedor">×</button><small>Fornecedor cadastrado</small><small x-text="selected?.formatted_document || 'Sem CPF/CNPJ'"></small></div>
    <div x-show="!selected && open && results.length" class="chm-supplier-picker__results" role="listbox">
        <template x-for="item in results" :key="item.id"><button type="button" @mousedown.prevent="select(item)" role="option"><strong x-text="item.name"></strong><small x-text="item.formatted_document || 'Sem CPF/CNPJ' "></small><em x-show="item.match_type !== 'exact'" x-text="item.match_type === 'strong' ? 'Fornecedor semelhante já cadastrado' : 'Possível correspondência'"></em></button></template>
    </div>
    <small x-show="!selected && $refs.name.value.length >= 2" class="chm-supplier-picker__manual">Fornecedor ainda não vinculado</small>
</div>
@once
<style>.chm-supplier-picker{position:relative}.chm-supplier-picker input[type=text],.chm-supplier-picker input:not([type]){width:100%}.chm-supplier-picker input[x-ref=document]{margin-top:8px}.chm-supplier-picker__results{position:absolute;z-index:1000;left:0;right:0;top:100%;max-height:240px;overflow:auto;border:1px solid #50647f;background:#202d42;box-shadow:0 10px 28px #08111e66}.chm-supplier-picker__results button{display:grid;width:100%;gap:2px;padding:10px;border:0;border-bottom:1px solid #3a4b63;text-align:left;color:#e7eef8;background:transparent;cursor:pointer}.chm-supplier-picker__results button:hover{background:#2c405e}.chm-supplier-picker small{display:block;color:#aebed3}.chm-supplier-picker em{font-size:11px;color:#e7c980;font-style:normal}.chm-supplier-picker__selected{margin-top:5px;padding:6px 8px;border:1px solid #4c8b67;background:#244638;color:#d5f0df}.chm-supplier-picker__selected button{float:right;border:0;background:none;color:#f0a2aa;font-size:18px;cursor:pointer}.chm-supplier-picker__loading,.chm-supplier-picker__manual{font-size:11px}</style>
<script>function supplierAutocomplete(){return{open:false,loading:false,results:[],selected:null,controller:null,requestId:0,suppressSearch:false,init(){if(this.$refs.id.value&&this.$refs.name.value)this.selected={id:this.$refs.id.value,name:this.$refs.name.value,formatted_document:this.$refs.document?.value||null}},setValue(ref,value){if(!this.$refs[ref])return;this.$refs[ref].value=value??'';this.$refs[ref].dispatchEvent(new Event('input',{bubbles:true}))},cancelRequest(){this.requestId++;this.controller?.abort();this.controller=null;this.loading=false},clearSelection(){this.selected=null;this.setValue('id','')},onFocus(){if(!this.selected)this.changed()},changed(){if(this.suppressSearch)return;const q=this.$refs.name.value.trim();if(this.selected){if(q===this.selected.name)return;this.clearSelection()}if(q.length<2){this.cancelRequest();this.open=false;this.results=[];return}this.cancelRequest();const requestId=++this.requestId;this.controller=new AbortController();this.loading=true;fetch(`{{ route('suppliers.search') }}?q=${encodeURIComponent(q)}`,{headers:{Accept:'application/json'},signal:this.controller.signal}).then(r=>r.json()).then(items=>{if(requestId!==this.requestId||this.selected)return;this.results=items;this.open=true}).catch(error=>{if(error.name!=='AbortError'&&requestId===this.requestId){this.results=[];this.open=false}}).finally(()=>{if(requestId===this.requestId)this.loading=false})},documentChanged(){if(this.suppressSearch)return;if(this.selected)this.clearSelection()},select(item){this.suppressSearch=true;this.cancelRequest();this.selected=item;this.results=[];this.open=false;this.setValue('id',item.id);this.setValue('name',item.name);this.setValue('document',item.formatted_document??item.document??'');this.$nextTick(()=>{this.suppressSearch=false})},clear(){this.cancelRequest();this.results=[];this.open=false;this.selected=null;this.setValue('id','');this.setValue('document','');this.$refs.name.focus();this.$nextTick(()=>this.changed())}}}</script>
@endonce
