<div x-data="supplierAutocomplete()" class="chm-supplier-picker" @keydown.escape="open=false">
    <input x-ref="name" name="supplier_name" value="{{ $value ?? '' }}" maxlength="255" placeholder="Nome do fornecedor" autocomplete="off" @input.debounce.300ms="changed()" @focus="changed()" aria-label="Fornecedor">
    <input x-ref="id" type="hidden" name="supplier_id" value="">
    <span x-show="loading" class="chm-supplier-picker__loading">Buscando fornecedores…</span>
    <div x-show="selected" class="chm-supplier-picker__selected"><strong x-text="selected?.name"></strong><button type="button" @click="clear()" aria-label="Limpar fornecedor">×</button><small x-text="selected?.formatted_document || 'Fornecedor cadastrado'"></small></div>
    <div x-show="open && results.length" class="chm-supplier-picker__results" role="listbox">
        <template x-for="item in results" :key="item.id"><button type="button" @click="select(item)" role="option"><strong x-text="item.name"></strong><small x-text="item.formatted_document || 'Sem CPF/CNPJ' "></small><em x-show="item.match_type !== 'exact'" x-text="item.match_type === 'strong' ? 'Fornecedor semelhante já cadastrado' : 'Possível correspondência'"></em></button></template>
    </div>
    <small x-show="!selected && $refs.name.value.length >= 2" class="chm-supplier-picker__manual">Fornecedor ainda não vinculado</small>
</div>
@once
<style>.chm-supplier-picker{position:relative}.chm-supplier-picker input[type=text],.chm-supplier-picker input:not([type]){width:100%}.chm-supplier-picker__results{position:absolute;z-index:1000;left:0;right:0;top:100%;max-height:240px;overflow:auto;border:1px solid #50647f;background:#202d42;box-shadow:0 10px 28px #08111e66}.chm-supplier-picker__results button{display:grid;width:100%;gap:2px;padding:10px;border:0;border-bottom:1px solid #3a4b63;text-align:left;color:#e7eef8;background:transparent;cursor:pointer}.chm-supplier-picker__results button:hover{background:#2c405e}.chm-supplier-picker small{display:block;color:#aebed3}.chm-supplier-picker em{font-size:11px;color:#e7c980;font-style:normal}.chm-supplier-picker__selected{margin-top:5px;padding:6px 8px;border:1px solid #4c8b67;background:#244638;color:#d5f0df}.chm-supplier-picker__selected button{float:right;border:0;background:none;color:#f0a2aa;font-size:18px;cursor:pointer}.chm-supplier-picker__loading,.chm-supplier-picker__manual{font-size:11px}</style>
<script>function supplierAutocomplete(){return{open:false,loading:false,results:[],selected:null,controller:null,changed(){if(this.selected){this.selected=null;this.$refs.id.value=''}let q=this.$refs.name.value.trim();if(q.length<2){this.open=false;this.results=[];return}this.controller?.abort();this.controller=new AbortController();this.loading=true;fetch(`{{ route('suppliers.search') }}?q=${encodeURIComponent(q)}`,{headers:{Accept:'application/json'},signal:this.controller.signal}).then(r=>r.json()).then(x=>{this.results=x;this.open=true}).catch(()=>{}).finally(()=>this.loading=false)},select(item){this.selected=item;this.$refs.id.value=item.id;this.$refs.name.value=item.name;this.open=false},clear(){this.selected=null;this.$refs.id.value='';this.$refs.name.focus()}}}</script>
@endonce
