<?php

return [
    'maintenance_type' => [
        'preventive' => 'Preventiva',
        'corrective' => 'Corretiva',
        'internal' => 'Interna',
        'external' => 'Externa',
    ],

    'service_type' => [
        'internal' => 'Interna',
        'external' => 'Externa',
    ],

    'execution_type' => [
        'internal' => 'Interna',
        'external' => 'Externa',
    ],

    'workflow_status' => [
        'open' => 'Aberta',
        'closed' => 'Fechada',
        'cancelled' => 'Cancelada',
    ],

    'vehicle_status' => [
        'active' => 'Ativo',
        'inactive' => 'Inativo',
        'unavailable' => 'Indisponível',
    ],

    'operational_status' => [
        'active' => 'Ativo',
        'inactive' => 'Inativo',
        'operational' => 'Operacional',
        'maintenance' => 'Em manutenção',
        'out_of_service' => 'Fora de operação',
        'unavailable' => 'Indisponível',
    ],

    'service_status' => [
        'waiting_parts' => 'Aguardando peças',
        'in_progress' => 'Em andamento',
        'waiting_approval' => 'Aguardando aprovação',
        'completed' => 'Concluída',
        'cancelled' => 'Cancelada',
    ],

    'stock_movement' => [
        'reversal' => 'Reversão',
        'reverted' => 'Revertido',
        'entry' => 'Entrada',
        'output' => 'Saída',
        'receipt' => 'Recebimento',
        'consumption' => 'Consumo',
        'adjustment' => 'Ajuste',
    ],

    'fuel_movement' => [
        'receipt' => 'Recebimento',
        'filling' => 'Abastecimento',
        'adjustment' => 'Ajuste',
        'cancellation' => 'Cancelamento',
    ],

    'fuel_filling_source' => [
        'internal_tank' => 'Tanque da unidade',
        'external_station' => 'Posto externo',
    ],
    'fuel_consumption_status' => [
        'calculado' => 'Calculado',
        'dados_insuficientes' => 'Dados insuficientes',
        'km_invalido' => 'KM inválido',
        'horas_invalidas' => 'Horas inválidas',
        'sem_km_hr' => 'Sem KM/HR',
    ],

    'vehicle_update_source' => [
        'dashboard_quick_update' => 'Atualização rápida',
        'operation_start' => 'Início de operação',
        'operation_close' => 'Fechamento de operação',
        'fuel_filling' => 'Abastecimento',
        'manual' => 'Manual',
        'maintenance' => 'Manutenção',
        'tire_measurement' => 'Medição de pneus',
    ],
    'audit_action' => [
        'created' => 'Criou',
        'create' => 'Criou',
        'store' => 'Criou',
        'updated' => 'Atualizou',
        'update' => 'Atualizou',
        'deleted' => 'Apagou',
        'delete' => 'Apagou',
        'cancelled' => 'Cancelou',
        'cancel' => 'Cancelou',
        'restored' => 'Restaurou',
        'restore' => 'Restaurou',
        'reversed' => 'Reverteu',
        'login' => 'Acessou',
        'logout' => 'Saiu',
        'receipt' => 'Registrou recebimento',
        'filling' => 'Registrou abastecimento',
        'status_changed' => 'Alterou status',
    ],

    'audit_module' => [
        'fuel' => 'Abastecimento',
        'maintenance' => 'Manutenção',
        'stock' => 'Estoque',
        'tires' => 'Pneus',
        'vehicles' => 'Veículos',
        'fleet' => 'Frota',
        'checklist' => 'Checklists',
        'checklists' => 'Checklists',
        'reports' => 'Relatórios',
        'access-control' => 'Controle de acessos',
        'access' => 'Controle de acessos',
        'portal' => 'Portal',
        'users' => 'Usuários',
        'operations' => 'Operações',
        'system' => 'Sistema',
    ],

    'audit_entity' => [
        'Vehicle' => 'Veículo',
        'MaintenanceRecord' => 'Ordem de manutenção',
        'MaintenanceRecordItem' => 'Serviço da manutenção',
        'MaintenanceRecordExtraCost' => 'Custo avulso',
        'StockItem' => 'Item de estoque',
        'StockMovement' => 'Movimentação de estoque',
        'FuelReceipt' => 'Recebimento de combustível',
        'FuelFilling' => 'Abastecimento de veículo',
        'FuelMovement' => 'Movimentação de combustível',
        'FuelTank' => 'Tanque',
        'Tire' => 'Pneu',
        'TireEntry' => 'Entrada de pneus',
        'TireMeasurement' => 'Medição de pneu',
        'TireRetread' => 'Recapagem',
        'TireInstallation' => 'Instalação de pneu',
        'VehicleOperation' => 'Operação do veículo',
        'ChecklistExecution' => 'Execução de checklist',
        'DailyChecklist' => 'Checklist diário',
        'User' => 'Usuário',
        'UserDivisionAccess' => 'Acesso do usuário',
        'Location' => 'Unidade',
        'Division' => 'Divisão',
    ],

    'audit_field' => [
        'id' => 'Identificador',
        'tenant_id' => 'Tenant',
        'division_id' => 'Divisão',
        'location_id' => 'Unidade',
        'vehicle_id' => 'Veículo',
        'fuel_tank_id' => 'Tanque',
        'fuel_product_id' => 'Produto',
        'procedure_id' => 'Procedimento',
        'stock_item_id' => 'Item de estoque',
        'maintenance_record_id' => 'Ordem de manutenção',
        'maintenance_record_item_id' => 'Serviço da manutenção',
        'name' => 'Nome',
        'plate' => 'Placa',
        'asset_code' => 'Prefixo',
        'status' => 'Status',
        'operational_status' => 'Status operacional',
        'workflow_status' => 'Situação da ordem',
        'service_status' => 'Status do serviço',
        'maintenance_category' => 'Categoria',
        'maintenance_type' => 'Tipo da manutenção',
        'current_km' => 'KM atual',
        'current_hours' => 'Horímetro atual',
        'performed_km' => 'KM registrado',
        'performed_hours' => 'Horímetro registrado',
        'quantity' => 'Quantidade',
        'quantity_liters' => 'Quantidade',
        'unit_cost' => 'Custo unitário',
        'total_cost' => 'Custo total',
        'amount' => 'Valor',
        'movement_type' => 'Tipo de movimentação',
        'created_at' => 'Data de criação',
        'updated_at' => 'Última alteração',
        'started_at' => 'Data de início',
        'finished_at' => 'Data de encerramento',
        'performed_at' => 'Data de execução',
        'cancelled_at' => 'Cancelado em',
        'opened_by' => 'Aberta por',
        'closed_by' => 'Finalizada por',
        'cancelled_by' => 'Cancelada por',
        'deleted_by' => 'Excluída por',
        'reason' => 'Motivo',
        'notes' => 'Observações',
        'description' => 'Descrição',
        'summary' => 'Resumo',
        'cancel_reason' => 'Motivo do cancelamento',
        'status_reason' => 'Motivo do status',
        'active' => 'Ativo',
    ],

    'user_profile' => [
        'admin' => 'Administrador',
        'tenant-admin' => 'Administrador do tenant',
        'manager' => 'Gestor',
        'supervisor' => 'Supervisor',
        'mechanic' => 'Mecânico',
        'driver' => 'Motorista',
    ],

    'tire_event' => [
        'installation' => 'Instalação',
        'removal' => 'Retirada',
        'measurement' => 'Medição',
        'retread' => 'Recapagem',
        'discard' => 'Descarte',
    ],
];